table People
	lineageTag: fb1e96ba-15a7-47de-a2e4-210658ef0563

	column Person
		dataType: string
		lineageTag: 7b75c330-01a1-45ab-8e04-6a5152d2957d
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 580e7d25-1599-48c6-917e-dfd6509eb6d3
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition People = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\TANMAY\Desktop\Harshita\Power BI\PBI Reports\Datasets\Sample - Superstore XLSX (1).xlsx"), null, true),
				    People_Sheet = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(People_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Person", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

